#!/bin/bash

MY_LOG_LEVEL=6
if [ $# > 0 ]; then MY_LOG_LEVEL=$1; fi

export MIOPEN_ENABLE_LOGGING=1
export MIOPEN_ENABLE_LOGGING_CMD=1
export MIOPEN_LOG_LEVEL=$MY_LOG_LEVEL
export MIOPEN_DEBUG_LOGGING_QUIETING_DISABLE=1 

