#!/bin/bash
# Runs a new ssh-agent and loads the user's key for github-EMU

if [[ "${BASH_SOURCE[0]}" != "${0}" ]] ; then

  if (( $(echo $SSH_AGENT_PID | wc -w) == 0 )); then
    eval "$(ssh-agent -s)"
  fi

  ssh-add -D
  ssh-add ~/.ssh/amdeng_rsa
else
  echo 'Error: sshe script must be sourced'
fi
